name: ci

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      -
        name: Checkout repo content
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push server
        uses: docker/build-push-action@v6
        with:
          push: true
          file: "Dockerfile3-10"
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/python-cuda-uv:3.10
      -
        name: Build and push server
        uses: docker/build-push-action@v6
        with:
          push: true
          file: "Dockerfile3-11"
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/python-cuda-uv:3.11
      -
        name: Build and push server
        uses: docker/build-push-action@v6
        with:
          push: true
          file: "Dockerfile3-12"
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/python-cuda-uv:3.12
